name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_tag:
        description: "Tag de pruebas"
        required: true
        default: "@todo"
        type: choice
        options:
          - "@todo"
          - "@registrarUsuario"

jobs:
  cypress-api:
    name: Cypress API Tests
    runs-on: ubuntu-latest

    env:
      CYPRESS_VALID_USER_EMAIL: ${{ secrets.CYPRESS_VALID_USER_EMAIL }}
      CYPRESS_VALID_USER_PASSWORD: ${{ secrets.CYPRESS_VALID_USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            npx cypress run --expose grepTags="${{ inputs.test_tag }}"
          else
            npx cypress run
          fi

      - name: Upload Cypress reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-api-reports
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
